-- Migration: Create attendance table for AttendTrack
-- Auto-generated by: supabase migration new create_attendance

-- ─── Table ───────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.attendance (
  id             UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id        UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  check_in_time  TIMESTAMPTZ NOT NULL,
  check_out_time TIMESTAMPTZ,
  total_duration INTEGER,
  date           DATE        NOT NULL,
  created_at     TIMESTAMPTZ DEFAULT NOW()
);

-- ─── Indexes ─────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_attendance_user_id
  ON public.attendance (user_id);

CREATE INDEX IF NOT EXISTS idx_attendance_user_date
  ON public.attendance (user_id, date DESC);

CREATE INDEX IF NOT EXISTS idx_attendance_user_active
  ON public.attendance (user_id, check_out_time)
  WHERE check_out_time IS NULL;

-- ─── Row Level Security ───────────────────────────────────────────────────────

ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own attendance"
  ON public.attendance FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own attendance"
  ON public.attendance FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own attendance"
  ON public.attendance FOR UPDATE
  USING (auth.uid() = user_id);
